"""Initial migration

Revision ID: 8b1115b2c813
Revises: 
Create Date: 2025-02-06 02:50:54.995787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b1115b2c813'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint('expense_cateogry_id_fkey', 'expense', type_='foreignkey')
    op.create_foreign_key(None, 'expense', 'category', ['category_id'], ['id'])
    op.drop_column('expense', 'cateogry_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('cateogry_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.create_foreign_key('expense_cateogry_id_fkey', 'expense', 'category', ['cateogry_id'], ['id'])
    op.drop_column('expense', 'category_id')
    # ### end Alembic commands ###
