"""Update category, budget, expense models

Revision ID: f94a90424b88
Revises: 9f8bfea97d2c
Create Date: 2026-03-11 04:29:25.119781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94a90424b88'
down_revision: Union[str, None] = '9f8bfea97d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget', 'amount_spent')
    op.add_column('category', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.create_unique_constraint('uix_user_category_name', 'category', ['user_id', 'name'])
    op.create_foreign_key(None, 'category', 'user', ['user_id'], ['id'])
    op.add_column('expense', sa.Column('expense_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense', 'expense_date')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_constraint('uix_user_category_name', 'category', type_='unique')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.drop_column('category', 'user_id')
    op.add_column('budget', sa.Column('amount_spent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
